# -*- coding: utf-8 -*-
"""Ecotype1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCyvQwewMSw2VF_iysX2dyN9MDEDSrge

---
# ***Mohamed Halith M K***
## **Title** : ***EcoType - Forest Cover Type Prediction Using Machine Learning***
### ***GUVI Mini Project- 3***
---

## Data Collection
"""

# importing libraries
import pandas as pd
import numpy as np

forest_df = pd.read_csv(r"/content/drive/MyDrive/cover_type.csv") # read csv file

forest_df.head()

forest_df.tail()

forest_df.shape

forest_df.columns

forest_df['Cover_Type'].unique()

forest_df['Cover_Type'].value_counts()

"""# **Data Understanding**"""

print(forest_df.shape)

forest_df.info()

forest_df.describe() # summary stat

print(forest_df.nunique()) # find nunique values in all columns

# find unique values in all columns
for i in forest_df.columns:
  print(i)
  print(forest_df[i].unique())
  print("-"*55)

for col in forest_df.columns:
    print(f"\nColumn: {col}")
    print(forest_df[col].value_counts())

forest_df.isnull().sum() # find null values

forest_df.duplicated().sum() # find duplicates

# Finding Class Imbalance
for i in forest_df.columns:
  print(forest_df[i].value_counts(normalize=True) * 100)

"""**Class distribution imbalance ratio**

|Ratio | Type               |
|------| -------------------|
|50:50 | Balanced           |
|60:40 | Mostly okay        |
|80:20 | worse → Imbalanced |
|95:5  | Highly imbalanced  |

**The biggest imbalance is in target column: Cover Type**
| Class             | Percentage |
| ----------------- | ---------- |
| Lodgepole Pine    | 70.65%     |
| Spruce/Fir        | 21.32%     |
| Aspen             | 2.10%      |
| Krummholz         | 1.48%      |
| Ponderosa Pine    | 1.48%      |
| Douglas-fir       | 1.48%      |
| Cottonwood/Willow | 1.48%      |

***This is a highly imbalanced multiclass dataset because***
  1. One class (Lodgepole Pine) dominates the dataset
  2. Several classes are below 2%
  3. Minority classes may be poorly predicted by ML models

# **Data Cleaning**
"""

df1 = forest_df.copy() # I'm taking copy for data cleaning

df1.head()

# find null values
print(df1.isnull().sum())

"""**There are no nulls**"""

df1.duplicated().sum()# find duplicates

"""**There are no duplicates**"""

# finding outliers ----> using visuals; importing libraries for visuals
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 10)) # create fig --> size, width

for i, col in enumerate(df1.columns):
    plt.subplot(4, 4, i + 1) # create subplot:- potition ===> grid 4*4
    sns.boxplot(y=df1[col], color='blue')
    plt.title(col)

plt.tight_layout()
plt.show()

numeric_cols = df1.select_dtypes(include='number').columns # taking numerical columns only

df_cleaned = df1.copy() # create separate dataframe for remove outliers


# outliers detection using IQR method
for col in numeric_cols:
  Q1 = df_cleaned[col].quantile(0.25) # 25% of values are below Q1.
  Q3 = df_cleaned[col].quantile(0.75) # 75% of values are below Q3.
  IQR = Q3 - Q1 # calulate IQR (Interquartile Range) 50% of values of data

  # define / setting outliers boundries
  lower_bound = Q1 - 1.5 * IQR
  upper_bound = Q3 + 1.5 * IQR

  # removing outliers in data
  df_cleaned = df_cleaned[
      (df_cleaned[col] >= lower_bound) &
      (df_cleaned[col] <= upper_bound)
  ]

# ensure outliers were removed
print("Original shape:", df1.shape)
print("After removing outliers:", df_cleaned.shape)

plt.figure(figsize=(15, 10)) # create fig --> size, width

for i, col in enumerate(df_cleaned.columns):
    plt.subplot(4, 4, i + 1) # create subplot:- potition ===> grid 4*4
    sns.boxplot(y=df_cleaned[col], color='blue')
    plt.title(col)

plt.tight_layout()
plt.show()

"""**Mager outliers were removed from dataset**"""

# Fix skewness in continuous variables using suitable transformations (e.g., log1p).
# Check skewness of numeric columns
skewness = df_cleaned.select_dtypes(include='number').skew()

# Sort by highest skewness
print(skewness.sort_values(ascending=False))

"""**Skew**
1. Skewness > 1 → Highly positively skewed
2. Skewness < -1 → Highly negatively skewed
3. Between -1 and 1 → Usually acceptable

**Reault of Skew Test**
| Feature                            | Skewness | Interpretation              |
| ---------------------------------- | -------: | --------------------------- |
| Aspect                             |    0.824 | Moderately skewed           |
| Vertical_Distance_To_Hydrology     |    0.758 | Moderately skewed           |
| Horizontal_Distance_To_Hydrology   |    0.679 | Slightly skewed             |
| Slope                              |    0.317 | Low skew                    |
| Horizontal_Distance_To_Fire_Points |    0.296 | Low skew                    |
| Hillshade_3pm                      |    0.091 | Nearly symmetric            |
| Horizontal_Distance_To_Roadways    |   -0.096 | Nearly symmetric            |
| Elevation                          |   -0.145 | Nearly symmetric            |
| Hillshade_Noon                     |   -0.237 | Low skew                    |
| Soil_Type                          |   -0.641 | Categorical/encoded feature |
| Hillshade_9am                      |   -0.649 | Moderate negative skew      |

**Skewness analysis indicated no severe skewness (|skewness| > 1) in the continuous variables after preprocessing.**

"""

df_cleaned.head()

# convert cleaned dataset into .csv file for further preprocessing
df_cleaned.to_csv("/content/drive/MyDrive/df_cleaned.csv", index=False)